language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true

install:
  - yarn global add codecov
  - yarn install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - yarn test -- --coverage
  - yarn test-e2e
  - codecov
  - yarn build